/**
 * Auto-generated build configuration
 * DO NOT EDIT MANUALLY - Generated by scripts/build.js
 */

export const BUILD_CONFIG = {
    isDev: false,
    mcpServerName: 'infinite_ask',
    ipcPort: 19823,
    displayName: 'Infinite Ask',
    version: '1.0.0'
};
